name: 'On-Demand EC2 Runner'
description: 'Launch an EC2 instance on-demand to use as a GitHub Actions runner.'
author: 'Guillem Casas'
branding:
  icon: 'server'
  color: 'blue'

inputs:
  mode:
    description: 'Action mode: "start" to launch an instance, "stop" to terminate one.'
    required: false
    default: 'start'
  aws-region:
    description: 'AWS region where the EC2 instance will be launched (e.g., eu-west-1)'
    required: false
    default: 'eu-west-1'
  ec2-ami:
    description: >-
      AMI ID to use for the EC2 instance (e.g., ami-1234567890abcdef0)
      Input required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 instance type (e.g., t2.micro, t3.micro)
      Input required if you use the 'start' mode.
    required: false
    default: 't2.micro'
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner, it is used to terminate the EC2 instance when the runner is not needed anymore.
      Input required if you use the 'stop' mode.
    required: false
  github-token:
    description: >-
      GitHub Token with the 'repo' scope assigned.
    required: true

outputs:
  label:
    description: >-
      Name of the github runner, is used in two cases:
      - To use as input of 'runs-on'.
      - To remove the runner from GitHub.
  ec2-instance-id:
    description: EC2 Instance Id, used to terminate the EC2 instance.

runs:
  using: 'node20'
  main: 'dist/index.js'
