name: 'On-Demand EC2 Runner'
description: 'Launch an EC2 instance on-demand to use as a GitHub Actions runner.'
author: 'Guillem Casas'
branding:
  icon: 'server'
  color: 'blue'

inputs:
  mode:
    description: 'Action mode: "start" to launch an instance, "stop" to terminate one.'
    required: false
    default: 'start'
  label:
    description: >-
      Label assigned to the GitHub runner, used to remove the runner from GitHub.
      Input required if you use the 'stop' mode.
    required: false
  ec2-ami:
    description: >-
      AMI ID to use for the EC2 instance (e.g., ami-1234567890abcdef0)
      Input required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 instance type (e.g., t2.micro, t3.micro)
      Input required if you use the 'start' mode.
    required: false
    default: 't2.micro'
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner, it is used to terminate the EC2 instance when the runner is not needed anymore.
      Input required if you use the 'stop' mode.
    required: false
  instance-running-timeout-seconds:
    description: 'Timeout in seconds to wait for the EC2 instance to reach "running" state.'
    required: false
    default: '300'
  block-device-name:
    description: >-
      Block device name for the EBS volume (e.g., /dev/sda1)
    required: false
    default: '/dev/sda1'
  ebs-volume-size:
    description: >-
      Size of the EBS volume in GiB (e.g., 8, 16)
    required: false
    default: '8'
  ebs-volume-type:
    description: >-
      Type of the EBS volume (e.g., gp2, gp3)
    required: false
    default: 'gp3'
  ebs-delete-on-termination:
    description: >-
      Whether to delete the EBS volume when the instance is terminated.
    required: false
    default: 'true'
  subnet-id:
    description: >-
      Subnet ID to use for the EC2 instance (e.g., subnet-1234567890abcdef0)
    required: false
  github-token:
    description: >-
      GitHub Token with the 'repo' scope assigned.
    required: true
  runner-timeout-minutes:
    description: 'Max minutes to wait for the GitHub runner to register.'
    required: false
    default: '4'
  runner-retry-seconds:
    description: 'Interval in seconds between checking the runner status.'
    required: false
    default: '2'
  runner-quiet-seconds:
    description: 'Initial wait time (in seconds) before starting to check runner status.'
    required: false
    default: '48'

outputs:
  label:
    description: >-
      Name of the github runner, is used in two cases:
      - To use as input of 'runs-on'.
      - To remove the runner from GitHub.
  ec2-instance-id:
    description: EC2 Instance Id, used to terminate the EC2 instance.

runs:
  using: 'node20'
  main: 'dist/index.js'
